# Site settings
title: Arjan Jassal | Front-end Developer Vancouver
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arjanjassal.com" # the base hostname & protocol for your site
github_username:  arjanj
exclude: ['node_modules', 'gulpfile.js', 'package.json', 'readme.md']

permalink: /:categories/:title/

# Build settings
markdown: kramdown

#page
# pages_list:
# 	About: '/about/'