<section class="about">
	<article class="about__wrapper">
		<p class="about__text">My name's Arjan, I'm a front-end developer and designer currently living in Vancouver. I strive to provide users with well-crafted, simple, and intuitive web experiences that help accomplish goals.</p>
		<div class="about__img">
			<img src="./assets/img/arjan-jassal.jpg" alt="Arjan Jassal standing there.">
		</div>
	</article>
	
	
</section>