<footer class="footer">
	<div class="u-wrapper">
		<p>
			Say <a class="footer__link" href="mailto:hello@arjanjassal.com">hello@arjanjassal.com</a> or
		</p>
		<p>
			Find me on
			<a class="footer__link" href="https://github.com/ArjanJ/" target="_blank">Github</a>
			<a class="footer__link" href="https://twitter.com/ArjanJassal/" target="_blank">Twitter</a>
			<a class="footer__link" href="https://codepen.io/arjancodes/" target="_blank">Codepen</a>
		</p>
	</div>
</footer>