<footer class="footer" id="footer" role="footer">
	<div class="u-wrapper">
		<span class="footer__text">Say <a class="home__link" href="mailto:hello@arjanjassal.com">hello@arjanjassal.com</a></span>
		<div class="footer__links">
			<a target="_blank" href="https://github.com/ArjanJ/" class="footer__links-link"><svg width="24" height="24"><use xlink:href="/assets/svg/icons.svg#github" /></svg></a>
			<a target="_blank" href="https://ca.linkedin.com/pub/arjan-jassal/97/695/275" class="footer__links-link"><svg width="24" height="24"><use xlink:href="/assets/svg/icons.svg#linkedin" /></svg></a>
			<a target="_blank" href="https://codepen.io/arjancodes/" class="footer__links-link"><svg width="26" height="26"><use xlink:href="/assets/svg/icons.svg#codepen" /></svg></a>
			<a target="_blank" href="https://www.behance.net/arjanjassal" class="footer__links-link"><svg width="24" height="24"><use xlink:href="/assets/svg/icons.svg#behance" /></svg></a>
			<a target="_blank" href="https://twitter.com/ArjanJassal/" class="footer__links-link"><svg width="24" height="24"><use xlink:href="/assets/svg/icons.svg#twitter" /></svg></a>
		</div>
	</div>
</footer>