<section class="home">
	<div class="home__wrapper">
		<h1 class="home__heading">Arjan Jassal - Vancouver Based Front-end Developer and Designer.</h1>
		<p>Check out some of my <a class="home__link" href="#work" data-scroll>work</a>, or see what I'm <a class="home__link" href="#about" data-scroll>about</a>.</p>
	</div>
	<div class="home__bg"></div>
	{% include "../partials/border.swig" %}
</section>