<section class="home">
	<div class="home__wrapper">
		<h1 class="home__heading">Arjan Jassal - Vancouver Based Front-end Developer and Designer.</h1>
	</div>
	<div class="home__links">
		<a href="" class="home__links-link">Email</a>
		<a href="" class="home__links-link">Github</a>
		<a href="" class="home__links-link">Twitter</a>
		<a href="" class="home__links-link">CodePen</a>
		<a href="" class="home__links-link">LinkedIn</a>
	</div>
</section>