{% extends "../layouts/default.swig" %}

{% block content %}

<section class="home">
	<article class="home__wrapper">
		<h1 class="home__heading">Arjan Jassal — Vancouver based front-end developer and designer.</h1>
		<p>
			<a href="http://codepen.io/arjancodes/" class="home__link">Codepen</a>
			<a href="https://github.com/arjanj" class="home__link">Github</a>
			<a href="https://twitter.com/arjanjassal" class="home__link">Twitter</a>
		</p>
	</article>
</section>

{% endblock %}