<section class="work">
	<div class="work__wrapper">
		<ul class="work__list">
			<li class="work__item">
				<div class="work__item-wrapper">
					<h2 class="work__item-heading">Bricks</h2>
					<p class="work__item-desc">Create justified image layouts like Google Images and Flickr.</p>
					<p>
						<a target="_blank" href="https://github.com/ArjanJ/bricks" class="c-button work__item-link">Github</a>
						<a target="_blank" href="http://bricks.arjanjassal.me/" class="c-button work__item-link">Live</a>
					</p>
				</div>
			</li>
			<li class="work__item">
				<div class="work__item-wrapper">
					<h2 class="work__item-heading">Readit</h2>
					<p class="work__item-desc">Browse Reddit with this slick single page application.</p>
					<p>
						<a target="_blank" href="https://github.com/ArjanJ/readit" class="c-button work__item-link">Github</a>
						<a target="_blank" href="http://readit.arjanjassal.me/" class="c-button work__item-link">Live</a>
					</p>
				</div>
			</li>
			<li class="work__item">
				<div class="work__item-wrapper">
					<h2 class="work__item-heading">Abby</h2>
					<p class="work__item-desc">A lightweight HTML/CSS boilerplate customizable with SCSS.</p>
					<p>
						<a target="_blank" href="https://github.com/ArjanJ/abby" class="c-button work__item-link">Github</a>
						<a target="_blank" href="http://abby.arjanjassal.me/" class="c-button work__item-link">Live</a>
					</p>
				</div>
			</li>
			<li class="work__item">
				<div class="work__item-wrapper">
					<h2 class="work__item-heading">Social Circles</h2>
					<p class="work__item-desc">An interactive infographic visualizing the size of social media networks.</p>
					<p>
						<a target="_blank" href="https://github.com/ArjanJ/social-circles" class="c-button work__item-link">Github</a>
						<a target="_blank" href="http://socialcircles.arjanjassal.me/" class="c-button work__item-link">Live</a>
					</p>
				</div>
			</li>
		</ul>
	</div>
</section>