<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Arjan Jassal | Front-end Developer Vancouver</title>

		<meta name="description" content="">

		<link href='https://fonts.googleapis.com/css?family=Roboto+Mono:400,300' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="./assets/css/bundle.css">
	</head>

	<body>

		{# {% include "../partials/header.swig" %} #}

		{% block content %}{% endblock %}		

		<script src="./js/bundle.js"></script>
	</body>
</html>